### PR TITLE
Update android studio a series of tutorials

### PR DESCRIPTION
**Pull request by whiskeyfei**
Sorry for the last commit about adnroid studio tutorials,I modified a little something,thanks!

### CODE REVIEW

**Comment by Princeton2u** [comment]
Why was this in my inbox? I did not open it when I noticed my return
address was no where to be found? Now I'm very inexperienced with all of
the cyber world including Android so if im wrong please explain, but as far
as I see this is not my mail in my email account! I think i have a bug to
or something but I've ran several antivirus apps and no one has found
anything so i cant help but think this is a bug?

Wayne Thornton (Boe)

**Comment by LLin233** [comment]
have you selected to “watch” this repo？ in that case, you have subscribed
This repo

**Comment by Princeton2u** [comment]
Sometimes when i get to a site for what ever reason i tend to explore to
understand (or try) lol, anyway yeah maybe i did, i kind of remember that,
lol. THanks for explaining.

Wayne Thornton (Boe)

**Comment by LLin233** [comment]
I have been confused when I played around in github the first time too...

dunkinboi73 notifications@github.com于2015年11月14日周六 下午11:58写道：

> Sometimes when i get to a site for what ever reason i tend to explore to
> understand (or try) lol, anyway yeah maybe i did, i kind of remember that,
> lol. THanks for explaining.
> 
> Wayne Thornton (Boe)

**Pull request merged**
